### ISSUE TITLE
what about streaming data?

### ISSUE THREAD

**Issue by mg1075** [kaliatech/dygraphs-dynamiczooming-example#2]
Cool project. 

Have you tried any of these with streaming data?

I opened an issue on the dygraphs github repository 
where for a range slider I had the problem of updating the range slider handles.
https://github.com/danvk/dygraphs/issues/578

http://jsfiddle.net/7w99t15x/

**Comment by kaliatech** [comment]
Thanks.

Doing live loading while zooming is possible, but the user interactions can get complex. For example, what do you expect to happen while the user is dragging the range selector and new data is still loading?  There are multiple possibilities.

I have started a live loading example in my dynamic data loading and zooming samples here that I might eventually publish. However, the live loading is mostly independent of the techniques I am showing here.  I'm going to close the issue here and add comment to your related issue on the official dygraphs repository that might help you.

**Comment by kaliatech** [comment]
In case still following this, I finally published an example showing the technique with continuous live data:
 * https://kaliatech.github.io/dygraphs-dynamiczooming-example/example6.html
